name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest  # Run on a macOS machine

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to latest version

      # Step 2: Unzip Cash App project (ensure the zip file is uploaded in the repo)
      - name: Unzip Cash App project
        run: |
          unzip "${{ github.workspace }}/Cash App.xcodeproj.zip" -d "${{ github.workspace }}"

      # Step 3: Debug - List files to confirm extraction
      - name: List files after unzipping
        run: |
          ls -R "${{ github.workspace }}"  # Recursively list all files to verify project.xcworkspace location

      # Step 4: Build the app with xcodebuild
      - name: Build iOS app
        run: |
          xcodebuild -workspace "${{ github.workspace }}/Cash App.xcodeproj/project.xcworkspace" \
            -scheme CashappSpoof \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "${{ github.workspace }}/build/CashAppSpoof.xcarchive" \
            -destination "generic/platform=iOS" \
            archive

      # Step 5: Export the .ipa file using the exportOptions.plist
      - name: Export .ipa file
        run: |
          xcodebuild -exportArchive \
            -archivePath "${{ github.workspace }}/build/CashAppSpoof.xcarchive" \
            -exportOptionsPlist "${{ github.workspace }}/exportOptions.plist" \
            -exportPath "${{ github.workspace }}/build"

      # Step 6: Upload the .ipa file as an artifact
      - name: Upload .ipa file as an artifact
        uses: actions/upload-artifact@v3  # Updated to latest version
        with:
          name: CashAppSpoof.ipa
          path: "${{ github.workspace }}/build/CashAppSpoof.ipa"
