name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest  # Run on a macOS machine

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to latest version

      # Step 2: Set up Xcode
      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      # Step 3: Build the app
      - name: Build iOS app
        run: |
          xcodebuild -workspace CashAppSpoof.xcworkspace \
            -scheme CashAppSpoof \
            -sdk iphoneos \
            -configuration Release \
            -archivePath ${{ github.workspace }}/build/CashAppSpoof.xcarchive \
            archive

      # Step 4: Export the .ipa file
      - name: Export .ipa file
        run: |
          xcodebuild -exportArchive \
            -archivePath ${{ github.workspace }}/build/CashAppSpoof.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath ${{ github.workspace }}/build

      # Step 5: Upload the .ipa file as an artifact
      - name: Upload .ipa file as an artifact
        uses: actions/upload-artifact@v3  # Updated to latest version
        with:
          name: CashAppSpoof.ipa
          path: build/CashAppSpoof.ipa
