name: Build and Export IPA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up certificates and provisioning profiles
      - name: Setup Certificates and Provisioning Profiles
        run: |
          echo "${{ secrets.CERTIFICATE }}" | base64 --decode > certificate.p12
          echo "${{ secrets.PROFILE }}" | base64 --decode > profile.mobileprovision
          security create-keychain -p "${{ secrets.KEY_PASSWORD }}" build.keychain
          security import certificate.p12 -A -k ~/Library/Keychains/build.keychain
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # Step 4: Set up Xcode environment
      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      # Step 5: Build and Archive the app
      - name: Build and Archive iOS App
        run: |
          xcodebuild -workspace "${{ github.workspace }}/Cash App.xcodeproj/project.xcworkspace" \
            -scheme CashappSpoof \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "${{ github.workspace }}/build/CashAppSpoof.xcarchive" \
            archive

      # Step 6: Export the .ipa file
      - name: Export .ipa file
        run: |
          xcodebuild -exportArchive \
            -archivePath "${{ github.workspace }}/build/CashAppSpoof.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "${{ github.workspace }}/build"

      # Step 7: Upload the .ipa file
      - name: Upload .ipa file
        uses: actions/upload-artifact@v3
        with:
          name: CashAppSpoof.ipa
          path: build/CashAppSpoof.ipa
