name: Build CashAppSpoof IPA

on:
  push:
    branches:
      - main  # Trigger the build when pushing to the main branch

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: apple-actions/setup-xcode@v3
      with:
        xcode-version: '15.4'  # Specify the Xcode version you're using

    - name: Install dependencies
      run: |
        # Install any dependencies if necessary, for example:
        # pod install
        # npm install (if using React Native)
        # swift package update
        # etc.

    - name: Set up code signing
      run: |
        # Ensure your certificate and provisioning profile are set up via GitHub Secrets
        # Example: `echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12`
        # Example: `echo $PROVISIONING_PROFILE | base64 --decode > profile.mobileprovision`

    - name: Build the app and export the IPA
      run: |
        # Build and archive the app
        xcodebuild clean \
          -workspace "CashAppSpoof.xcworkspace" \
          -scheme "CashAppSpoof" \
          CODE_SIGN_IDENTITY="iPhone Developer" \
          PROVISIONING_PROFILE_SPECIFIER="<YOUR_PROVISIONING_PROFILE>" \
          CODE_SIGN_STYLE="Automatic" \
          -configuration Release

        # Export the IPA using the exportOptions.plist file
        xcodebuild -exportArchive \
          -archivePath $CI_PROJECT_DIR/build/Build/Products/Release-iphoneos/CashAppSpoof.xcarchive \
          -exportOptionsPlist "/path/to/your/exportOptions.plist" \
          -exportPath $CI_PROJECT_DIR/build/IPA

        # Set a path to the generated IPA
        IPA_PATH="$CI_PROJECT_DIR/build/IPA/CashAppSpoof.ipa"
        echo "IPA file generated at $IPA_PATH"

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v3
      with:
        name: CashAppSpoof.ipa
        path: $CI_PROJECT_DIR/build/IPA/CashAppSpoof.ipa
